begin;
create temp table qa_ops(n integer,id uuid);
insert into qa_ops select n,gen_random_uuid() from generate_series(1,6) n;
grant select on qa_ops to authenticated;
insert into public.baseline_members(id,name) select id,'QA Operations '||n from qa_ops;
insert into auth.users(id,email,raw_user_meta_data,aud,role,created_at,updated_at) select id,'qa-'||id||'@example.invalid',jsonb_build_object('roster_id',id,'phone','07000000001','name_confirmation',true),'authenticated','authenticated',now(),now() from qa_ops;
create temp table qa_ids(k text,id bigint);
grant select on qa_ids to authenticated;
with ev as(insert into public.baseline_events(name,date,round_number,member_price,guest_price,course_member_price,max_players,cancellation_terms) values('QA Operations R1','2027-04-01',1,35,40,10,4,'Late withdrawal fees require committee review') returning id)insert into qa_ids select 'r1',id from ev;
with ev as(insert into public.baseline_events(name,date,round_number) values('QA Operations R2','2027-05-01',2) returning id)insert into qa_ids select 'r2',id from ev;
with ev as(insert into public.baseline_events(name,date,event_type,member_price) values('QA Operations pairs','2027-06-01','pairs',45) returning id)insert into qa_ids select 'pairs',id from ev;
with ev as(insert into public.baseline_events(name,date,event_type,member_price) values('QA Operations social','2027-11-01','social',12) returning id)insert into qa_ids select 'social',id from ev;
select set_config('request.jwt.claim.sub',(select id::text from public.profiles where is_admin limit 1),true);
update public.profiles set handicap=20 where id in(select id from qa_ops);
do $$begin begin update public.profiles set handicap=37 where id=(select id from qa_ops where n=1);raise exception 'Starting cap missing';exception when raise_exception then if sqlerrm not like 'Starting handicap must be 0 to 36%' then raise;end if;end;end $$;
set local role authenticated;
do $$declare eid bigint; u uuid;rev int;result jsonb;payload jsonb;snapshot jsonb;charge jsonb;begin
 select id into eid from qa_ids where k='r1';select id into u from qa_ops where n=1;
 perform public.baseline_operations('settings','{"membership_fee":20,"create_membership_charges":true,"bank_instructions":"QA only — not a real bank"}');
 for i in 1..5 loop perform public.baseline_submit_rsvp(jsonb_build_object('event_id',eid,'user_id',(select id from qa_ops where n=i),'attending',true,'buggy',i<=2));end loop;
 result:=public.baseline_operations('admin');
 if (select count(*) from jsonb_array_elements(result->'charges') x where (x->>'event_id')::bigint=eid)<>4 then raise exception 'Waiting player was charged';end if;
 perform public.baseline_save_tee_times(eid,jsonb_build_array(jsonb_build_object('time','13:00','players',(select jsonb_agg(id order by n) from qa_ops where n<=4))));
 perform public.baseline_save_tee_times(eid,jsonb_build_array(jsonb_build_object('time','13:08','players',(select jsonb_agg(id order by n) from qa_ops where n<=4))));
 select x into charge from jsonb_array_elements(result->'charges') x where (x->>'event_id')::bigint=eid and x->>'user_id'=u::text;
 perform public.baseline_operations('save_charge',charge||'{"received":35,"clear_report":true}');
 begin perform public.baseline_operations('save_charge',charge||'{"received":35}');raise exception 'Stale payment write allowed';exception when raise_exception then if sqlerrm<>'Payment changed. Reload before saving' then raise;end if;end;
 perform public.baseline_submit_rsvp(jsonb_build_object('event_id',eid,'user_id',u,'attending',false));
 result:=public.baseline_operations('admin');
 if not exists(select 1 from jsonb_array_elements(result->'charges') x where x->>'user_id'=u::text and (x->>'event_id')::bigint=eid and (x->>'received')::numeric=35 and (x->>'cancellation_review')::boolean) then raise exception 'Withdrawal lost money history';end if;
 if not exists(select 1 from public.baseline_rsvps where event_id=eid and user_id=(select id from qa_ops where n=5) and attending and not reserve) then raise exception 'Waiting list not promoted';end if;
 select jsonb_agg(jsonb_build_object('user_id',id,'status',case when n=6 then 'dnp' else 'played' end,'points',case when n=6 then null else 40-n*2 end)) into payload from qa_ops;
 result:=public.baseline_league_save_round(eid,payload,null,true,(public.baseline_league_admin()->>'revision')::int);
 snapshot:=(result->'rounds')->0;
 result:=public.baseline_manual_handicap(u,2,8,'Committee agreed exceptional cut',(result->>'revision')::int);
 if result->'rounds'->0<>snapshot then raise exception 'Manual future adjustment rewrote earlier results';end if;
 if not exists(select 1 from jsonb_array_elements(result->'players') p,jsonb_array_elements(p->'adjustments') x where p->>'id'=u::text and (x->>'handicap')::numeric=8) then raise exception 'Manual adjustment missing from admin';end if;
 result:=public.baseline_league_save_round((select id from qa_ids where k='r2'),payload,null,true,(result->>'revision')::int);
 if not exists(select 1 from jsonb_array_elements(result->'rounds') r,jsonb_array_elements(r->'results') x where (r->>'round_number')::int=2 and x->>'user_id'=u::text and (x->>'handicap')::numeric=8) then raise exception 'Round did not use manual value';end if;
 begin perform public.baseline_manual_handicap(u,2,10,'Cannot change the past',(result->>'revision')::int);raise exception 'Published round override allowed';exception when raise_exception then if sqlerrm<>'Choose an unpublished future round. Earlier results cannot be changed here' then raise;end if;end;
end $$;
reset role;
select set_config('request.jwt.claim.sub',(select id::text from qa_ops where n=1),true);
set local role authenticated;
do $$declare eid bigint; result jsonb; pair_id bigint;begin
 select id into eid from qa_ids where k='r1';
 result:=public.baseline_operations('member',jsonb_build_object('event_id',eid));
 if exists(select 1 from jsonb_array_elements(result->'charges') x where x->>'user_id'<>(select id::text from qa_ops where n=1)) then raise exception 'Another member financial record leaked';end if;
 if jsonb_array_length(result->'changes')<>1 then raise exception 'Tee change missing';end if;
 begin perform public.baseline_operations('admin');raise exception 'Member accessed admin';exception when raise_exception then if sqlerrm<>'Organiser access required' then raise;end if;end;
 begin perform public.baseline_manual_handicap((select id from qa_ops where n=1),3,7,'Unauthorised override',0);raise exception 'Member changed handicap';exception when raise_exception then if sqlerrm<>'Organiser access required' then raise;end if;end;
 begin perform public.baseline_operations('settings','{}');raise exception 'Member changed bank details';exception when raise_exception then if sqlerrm<>'Organiser access required' then raise;end if;end;
 begin perform * from baseline_private.charges;raise exception 'Private charges readable';exception when insufficient_privilege then null;end;
 begin perform public.baseline_submit_rsvp(jsonb_build_object('event_id',eid,'attending',true));raise exception 'Terms bypassed';exception when raise_exception then if sqlerrm<>'Accept the cancellation terms before booking' then raise;end if;end;
 perform public.baseline_submit_rsvp(jsonb_build_object('event_id',(select id from qa_ids where k='social'),'attending',true,'buggy',true,'preferred_time','First'));
 if exists(select 1 from public.baseline_rsvps where event_id=(select id from qa_ids where k='social') and (buggy or preferred_time is not null)) then raise exception 'Social event stored golf options';end if;
 perform public.baseline_submit_rsvp(jsonb_build_object('event_id',(select id from qa_ids where k='pairs'),'attending',true));
 perform public.baseline_operations('pair',jsonb_build_object('event_id',(select id from qa_ids where k='pairs')));
 perform public.baseline_operations('invite_guest',jsonb_build_object('event_id',(select id from qa_ids where k='pairs'),'name','QA Guest Operations','phone','07000000003','handicap',25));
end $$;
reset role;
select set_config('request.jwt.claim.sub',(select id::text from qa_ops where n=2),true);
set local role authenticated;
select public.baseline_submit_rsvp(jsonb_build_object('event_id',(select id from qa_ids where k='pairs'),'attending',true));
select public.baseline_operations('pair',jsonb_build_object('event_id',(select id from qa_ids where k='pairs'),'partner_id',(select id from qa_ops where n=1)));
reset role;
select set_config('request.jwt.claim.sub',(select id::text from qa_ops where n=1),true);
set local role authenticated;
do $$declare result jsonb;pid bigint;begin
 result:=public.baseline_operations('member',jsonb_build_object('event_id',(select id from qa_ids where k='pairs')));pid:=((result->'pairs')->0->>'id')::bigint;
 perform public.baseline_operations('pair',jsonb_build_object('event_id',(select id from qa_ids where k='pairs'),'mode','accept','id',pid));
end $$;
reset role;
select set_config('request.jwt.claim.sub',(select id::text from public.profiles where is_admin limit 1),true);
set local role authenticated;
do $$declare result jsonb;gid uuid;begin
 result:=public.baseline_operations('admin');select (x->>'id')::uuid into gid from jsonb_array_elements(result->'guests') x where x->>'name'='QA Guest Operations';
 perform public.baseline_operations('approve_guest',jsonb_build_object('id',gid,'approve',true,'handicap',24));
 begin perform public.baseline_save_tee_times((select id from qa_ids where k='pairs'),jsonb_build_array(jsonb_build_object('time','13:00','players',jsonb_build_array((select id from qa_ops where n=1))),jsonb_build_object('time','13:08','players',jsonb_build_array((select id from qa_ops where n=2)))));raise exception 'Playing pair split allowed';exception when raise_exception then if sqlerrm<>'Keep confirmed playing partners in the same tee group' then raise;end if;end;
 perform public.baseline_operations('task',jsonb_build_object('event_id',(select id from qa_ids where k='pairs'),'task','Prizes assigned','owner','QA organiser','done',true));
 perform public.baseline_operations('item','{"kind":"expense","description":"QA golf prizes","owner":"QA organiser","amount":25,"quantity":1}');
end $$;
reset role;
-- Claim an approved guest name through the real account trigger.
insert into auth.users(id,email,raw_user_meta_data,aud,role,created_at,updated_at)
select gen_random_uuid(),'qa-guest-'||g.id||'@example.invalid',jsonb_build_object('roster_id',g.member_id,'phone',g.phone,'name_confirmation',true),'authenticated','authenticated',now(),now() from baseline_private.guest_requests g where g.name='QA Guest Operations';
do $$declare u uuid;begin
 select a.user_id into u from public.baseline_member_accounts a join baseline_private.guest_requests g on g.member_id=a.member_id where g.name='QA Guest Operations';
 if u is null or not exists(select 1 from public.profiles where id=u and handicap=24) then raise exception 'Guest claim did not apply approved handicap';end if;
 if not exists(select 1 from baseline_private.member_types where user_id=u and category='guest') then raise exception 'Guest category lost';end if;
 if exists(select 1 from baseline_private.charges where user_id=u and scope='membership:2027') then raise exception 'Guest charged annual membership';end if;
end $$;
-- Booking ownership, reservation confirmation, and release notices are separate.
select set_config('request.jwt.claim.sub',(select id::text from public.profiles where is_admin limit 1),true);
set local role authenticated;
select public.baseline_submit_rsvp(jsonb_build_object('event_id',(select id from qa_ids where k='r1'),'user_id',(select id from qa_ops where n=1),'attending',true,'buggy',true));
select public.baseline_submit_rsvp(jsonb_build_object('event_id',(select id from qa_ids where k='r1'),'user_id',(select id from qa_ops where n=5),'attending',false));
select public.baseline_save_tee_times((select id from qa_ids where k='r1'),jsonb_build_array(jsonb_build_object('time','13:08','players',(select jsonb_agg(id order by n) from qa_ops where n<=4))));
reset role;
select set_config('request.jwt.claim.sub',(select id::text from qa_ops where n=1),true);
set local role authenticated;
select public.baseline_buggy_details((select id from qa_ids where k='r1'),true,false);
select public.baseline_operations('confirm_buggy',jsonb_build_object('event_id',(select id from qa_ids where k='r1'),'confirmed',true));
do $$declare r jsonb;begin
 r:=public.baseline_buggy_details((select id from qa_ids where k='r1'),false,false);
 if r->>'confirmed_at' is null then raise exception 'Course booking confirmation missing';end if;
 perform public.baseline_buggy_details((select id from qa_ids where k='r1'),false,true);
 if jsonb_array_length(public.baseline_reservation_notices((select id from qa_ids where k='r1')))=0 then raise exception 'Released booking lost reservation reminder';end if;
end $$;
reset role;
rollback;
select 'PASS: starting cap, private payments, stale write protection, paid withdrawal retention, waitlist promotion, tee change notices, future-only handicap overrides, unchanged earlier results, downstream scoring, member denials, cancellation acceptance, social fields, playing-pair acceptance and integrity, guest approval and signup, buggy confirmation and release alerts, checklist and expenses. All fixtures rolled back.' verification;
